-- Initialize Database "BikeStore"

-- CREATE DATABASE "BikeStore";

CREATE TABLE "Customers"(
	custID SMALLSERIAL PRIMARY KEY.
	nameF VARCHAR(20) NOT NULL,
	nameL VARCHAR(30) NOT FULL
);

CREATE TABLE "Phone Number"(
	phID SMALLSERIAL PRIMARY KEY,
	phNum VARCHAR(30) NOT NULL,
	custID INT REFERENCES "Customers"
);

CREATE TABLE "Inventory"(
	invID SERIAL PRIMARY KEY,
	invName VARCHAR(20) NOT NULL,
	invModel VARCHAR(30),
	invCost NUMERIC(6,2) NOT NULL
);

